### ISSUE TITLE
Add Classic HTML Variant with Default Tailwind Components

### ISSUE THREAD

**Issue by M-U-C-K-A** [tommyjepsen/twblocks#3]
I'm an avid user of TWBlocks and I appreciate the work put into making these blocks available. 

I suggest adding a classic HTML variant with default Tailwind components. 
Currently, TWBlocks are primarily designed for React projects, which may limit usage. 
By adding this variant, we can cater to a wider audience and enhance TWBlocks' versatility.

Thanks!

**Comment by tommyjepsen** [comment]
Hi,

Thanks for the suggestion, but this is library solely focused on using React now, since it's implementing components from shadcn.
