### ISSUE TITLE
Implement Light/Dark Theme on All Pages

### ISSUE THREAD

**Issue by M-U-C-K-A** [tommyjepsen/twblocks#4]
I'm an avid user of TWBlocks and I appreciate the work put into making these blocks available.

I have a suggestion to enhance the user experience. Currently, the light/dark theme toggle is available only on the homepage. I propose extending this feature to all pages for consistency and improved accessibility.

By implementing the light/dark theme toggle across all pages, users can customize their browsing experience according to their preference seamlessly. This enhancement would elevate TWBlocks and provide users with a cohesive experience throughout the entire site.

Thanks!

**Comment by tommyjepsen** [comment]
Thanks! Makes tons of sense. I've changed it to be available on all pages now.
